title: Dylan
email: dylan.elliott@gmail.com
description: >-
  BLOG
baseurl: ""
url: "https://dyldog.github.io"
github_username: dyldog
remote_theme: riggraz/no-style-please
theme_config:
  date_format: "%Y-%m-%d"
  back_home_text: "←"
plugins:
  - jekyll-feed
